### ISSUE TITLE
License for this Project

### ISSUE THREAD

**Issue by mogria** [mogria/rtsh#1]
We probably should choose a License for this Project.

Some Options: (ordered by my personal preference)
- GPLv2+
- MIT, BSD
- Something else?

A thing to consider is that wetty-cli already has the MIT license because it's purely based on https://github.com/krishnasrinivas/wetty

So just licensing the project MIT would be the path of least resistance. But I'm worried that in the future someone might just take the code, use it for their own commercial advantage and not even give some code back. The drawback of the GPL is that people certain people might not even consider this project, because of this restriction.

Additionally, after we chose the license we should add it to the project and update some files in which you can set a license (for example wetty-cli/package.json etc.).

@wtjerry I'd like to hear your opinion about this.

**Comment by Che4ter** [comment]
I would choose gpl

**Comment by mogria** [comment]
After talking with @wtjerry, he also thinks that the GPL would be a viable option. I'll opt for licensing this project GPLv2+, so this project is compatible to projects licenced GPLv2 and GPLv3 (the GPLv3 is not backwards compatible)

Although for the sake of simplicity I'll keep the wetty-cli part licensed under the MIT for now.
